image: debian:buster-slim

stages:
  - build

before_script:
  - cd build
  - ./fastocloud_env/fast_build_fastocloud_env_for_dev.sh

build:
  stage: build

  script:
    - ./build.py --release

  tags:
    - fastogt

